### ISSUE TITLE
paridisp

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/ifelse#1]
Creare un programma paridisp.py che chieda
all'utente di inserire un numero intero
e quindi dica se e' pari o dispari

**Comment by Teodoro777** [comment]
Fatto

2016-02-06 19:30 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
Non mi piace che fai tutto insieme, il fatto che il linguaggio lo permetta non è detto che sia una buona idea

prima l'input, poi l'elaborazione

**Comment by Teodoro777** [comment]
Ah vabbè quindi torno alle variabili?

Il giorno 6 febbraio 2016 18:43, Fabio Z Tessitore <notifications@github.com
