### ISSUE TITLE
primo grado

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/ifelse#3]
Scrivi un programma che trovi la soluzione a equazioni di primo grado
nella forma ax+b=0, con a e b interi.

Il programma dovrebbe tener conto dei casi particolari: a, b o entrambi nulli.

**Comment by Teodoro777** [comment]
Due domande: 1- come si fa ad andare a capo in python? 2- la funzione
input() va bene per i float?

2016-02-06 19:31 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
Puoi usare \n
No. Input restituisce interi

Il domenica 7 febbraio 2016, Teodoro <notifications@github.com> ha scritto:

**Comment by Teodoro777** [comment]
Fatto. Qui come si fa per mostrare solo 2 cifre decimali?

2016-02-07 13:14 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
Puoi usare la stampa formattata stile C
```python
"%.2f" % (valore_float, )
```
oppure la funzione format delle stringhe python
```python
"{:.2f}".format(valore_float)
```

**Comment by FabioZTessitore** [comment]
Il tuo programma non è in grado di risolvere l'equazione
```python
3x+0=0
```

**Comment by FabioZTessitore** [comment]
comincia da qui che è più facile

**Comment by Teodoro777** [comment]
Vabbè è facilissimo, ora credo di aver implementato tutte le possibili
condizioni..
Comunque com'è che print funziona sia se le metto le parentesi sia senza?!

2016-02-07 19:23 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
sarà pure facilissimo ma non ci siamo. Le prime due condizioni possono essere trattate contemporaneamente.

Quando ti do dei consigli cerca di metterli in pratica. Ripeto: parti dalle condizioni sfavorevoli

**Comment by Teodoro777** [comment]
Sì ma esce -0, io ho messo un'altra condizione perchè mi da fastidio il -
davanti lo 0

Il giorno 7 febbraio 2016 21:42, Fabio Z Tessitore <notifications@github.com

**Comment by FabioZTessitore** [comment]
ok, se questa è la ragione va bene.
ti ho mandato una soluzione alternativa, mettendo prima i casi negativi

**Comment by Teodoro777** [comment]
Ok, comunque com'è che print funziona sia se le metto le parentesi sia
senza?!

2016-02-07 22:03 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
we, ti ho risposto prima

**Comment by Teodoro777** [comment]
No mi avete risposto per il programma..

2016-02-07 22:10 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
copio ed incollo:

> ps. riguardo a print, è stata fatta così. Invece la versione 3 obbliga l'uso delle parentesi

**Comment by Teodoro777** [comment]
Ahh comunque ho letto che la versione 3, nelle divisioni trasforma
automaticamente la variabile in float, comodo no?

Il giorno 9 febbraio 2016 22:07, Fabio Z Tessitore <notifications@github.com

**Comment by FabioZTessitore** [comment]
Cmq in python2 print è un comando dell'interprete. Però ci possono essere problemi perché l'istruzione:
```python
print ("Hello", "world")
```
è ambigua. Deve stampare la tupla di due elementi (le parentesi **non** sono di print) oppure deve stampare la concatenazione delle stringhe (le parentesi *appartengono* a print).
Nella versione 3 print diventa una funzione e quindi vuole le parentesi

ps. riguardo alle divisioni, si lo so, ma non sono sicuro sia una cosa buona. E' una cosa

**Comment by Teodoro777** [comment]
Ok capito

Il giorno 9 febbraio 2016 22:13, Fabio Z Tessitore <notifications@github.com
