### ISSUE TITLE
secondo grado

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/ifelse#4]
Scrivi un programma che trovi le soluzioni a equazioni di secondo grado
nella forma ax^2+bx+c=0, con a, b e c interi.
Il programma dovrebbe tener conto dei casi particolari.

Per il calcolo della radice quadrata si puo' utilizzare la funzione `sqrt()`
della libreria matematica math
```python
import math

... math.sqrt() ...
```

**Comment by Teodoro777** [comment]
Vedete se c'è qualche caso che non risolve..

Il sabato 6 febbraio 2016, Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by Teodoro777** [comment]
Sembra vada bene

Il giorno 7 febbraio 2016 19:09, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
finisci questo esercizio così andiamo avanti. Come prossimo argomento, se vuoi, ci sono le prime cose sull'HTML

**Comment by Teodoro777** [comment]
Sisi mi va bene... Comunque vedete voi, ma il programma funziona sia per
equazioni in forma normale, sia spurie e pure

Il giorno 9 febbraio 2016 13:43, Fabio Z Tessitore <notifications@github.com

**Comment by FabioZTessitore** [comment]
il programma non risponde alle mie domande haha

**Comment by Teodoro777** [comment]
Cosa intendete? Ahah

2016-02-09 18:58 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
non hai letto i commenti nel codice?

**Comment by Teodoro777** [comment]
Ahahahahaha mo aggiusto ma comunque come posso nascondere quel .0 quando il
numero non è decimale?

2016-02-09 19:14 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
intendi nei risultati? se è così abituati a tenerlo. Poi ne riparliamo se arriviamo a fare qualche simulazione numerica

**Comment by Teodoro777** [comment]
Ok comunque mo dovrebbe andar bene

Il giorno 9 febbraio 2016 19:30, Fabio Z Tessitore <notifications@github.com

**Comment by FabioZTessitore** [comment]
Diciamo che va bene, ci sono tre cose da aggiustare:
1. alla riga 19, volevi dire c=0, invece hai scritto b=0
2. alla riga 32 non è necessario calcolare sqrt(d) se d è zero, ti pare?
3. il calcolo di d lo avrei messo nell'else alla riga 27, prima non è necessario

**Comment by Teodoro777** [comment]
Si tra poco aggiusto i dettagli

Il martedì 9 febbraio 2016, Fabio Z Tessitore <notifications@github.com> ha
scritto:
